
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kastel
 */
public class Dice extends javax.swing.JFrame
{

	private List<JLabel> lbl_list;

	/**
	 * Creates new form Dice
	 */
	public Dice()
	{
		lbl_list = new ArrayList<>();
		initComponents();
		this.setLocationRelativeTo(null);
		IntegerDocumentFilter.addTo(coins_num_txtbox);
		IntegerDocumentFilter.addTo(dime_txtb);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        coins_num_txtbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_throwCoin = new javax.swing.JButton();
        dime_txtb = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        runHigherLower = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Throw dice");

        coins_num_txtbox.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                coins_num_txtboxKeyTyped(evt);
            }
        });

        jLabel1.setText("Set number of dices:");

        btn_throwCoin.setText("Throw Dieces");
        btn_throwCoin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_throwCoinActionPerformed(evt);
            }
        });

        jMenu1.setText("LowerHigher");

        runHigherLower.setText("Run");
        runHigherLower.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runHigherLowerActionPerformed(evt);
            }
        });
        jMenu1.add(runHigherLower);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Head or Tails");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dieces");
        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dime_txtb)
                    .addComponent(coins_num_txtbox, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_throwCoin)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_throwCoin)
                    .addComponent(coins_num_txtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dime_txtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coins_num_txtboxKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_coins_num_txtboxKeyTyped
    {//GEN-HEADEREND:event_coins_num_txtboxKeyTyped

    }//GEN-LAST:event_coins_num_txtboxKeyTyped

    private void btn_throwCoinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_throwCoinActionPerformed
    {//GEN-HEADEREND:event_btn_throwCoinActionPerformed
		deleteDiecesfromFrame();
		int x = 10;
		int j = 0;
		int dice_dim = 3;
		
		Random r = new Random();
		if (!coins_num_txtbox.getText().isEmpty() && !dime_txtb.getText().isEmpty())
		{
			if (Integer.parseInt(coins_num_txtbox.getText()) < 97 && Integer.parseInt(dime_txtb.getText()) > 2)
			{
				dice_dim = Integer.parseInt(dime_txtb.getText());
				for (int i = 0; i < Integer.parseInt(coins_num_txtbox.getText()); i++)
				{
					if (i % 12 == 0 && i != 0)
					{
						x = x + 20;
						j = 0;
					}

					JLabel jab = new JLabel();

					int num = r.nextInt(dice_dim) + 1;
					jab.setText(String.valueOf(num));

					jab.setBounds(x, 30 + j * 20, 100, 30);
					lbl_list.add(jab);
					this.add(jab);
					j++;
				}
				this.revalidate();
				this.repaint();
			}
			else
			{
				JOptionPane.showMessageDialog(null, "You can't throw more than 96 coins!\nDimension of dice need to be greater than 3.", "Incorrect values!", JOptionPane.ERROR_MESSAGE);
			}
		}
		else
		{
			JOptionPane.showMessageDialog(null, "Enter right dice dimension and enter how many dices you want to throw.", "Fill blank fields!", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btn_throwCoinActionPerformed

    private void runHigherLowerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runHigherLowerActionPerformed
    {//GEN-HEADEREND:event_runHigherLowerActionPerformed
		this.setVisible(false);
		StartWindow.highlow.setVisible(true);
    }//GEN-LAST:event_runHigherLowerActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new Dice().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_throwCoin;
    private javax.swing.JTextField coins_num_txtbox;
    private javax.swing.JTextField dime_txtb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem runHigherLower;
    // End of variables declaration//GEN-END:variables

	private void deleteDiecesfromFrame()
	{
		for (JLabel lbl : lbl_list)
		{
			lbl.setVisible(false);
		}
		lbl_list.clear();
	}
}
