/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * First window that user encounter. You can choose here which game you want to play.
 *
 * @author kastel
 */
public class StartWindow extends javax.swing.JFrame
{

	//All games avaiable. They are static beacause you can change game from any point of game
	public static HigherLower highlow;
	public static HeadTail headtail;
	public static Dice dice;
	public static Whatnumber whatnum;

	/**
	 * Creates new form StartWindow
	 */
	public StartWindow()
	{
		initComponents();
		this.setLocationRelativeTo(null); //set it at the center of the screen
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btn_lowehigh = new javax.swing.JButton();
        btn_headtail = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_dice = new javax.swing.JButton();
        btn_whatnumber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RandomGames");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btn_lowehigh.setBackground(new java.awt.Color(102, 153, 255));
        btn_lowehigh.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btn_lowehigh.setText("Lower or Higher");
        btn_lowehigh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_lowehighActionPerformed(evt);
            }
        });

        btn_headtail.setBackground(new java.awt.Color(102, 153, 255));
        btn_headtail.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btn_headtail.setText("Head/Tails");
        btn_headtail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_headtailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose the game:");

        btn_dice.setBackground(new java.awt.Color(102, 153, 255));
        btn_dice.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btn_dice.setText("Throw dice");
        btn_dice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_diceActionPerformed(evt);
            }
        });

        btn_whatnumber.setBackground(new java.awt.Color(102, 153, 255));
        btn_whatnumber.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        btn_whatnumber.setText("What number?");
        btn_whatnumber.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_whatnumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_lowehigh, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(btn_headtail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_whatnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_headtail, btn_lowehigh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_lowehigh)
                .addGap(18, 18, 18)
                .addComponent(btn_headtail)
                .addGap(18, 18, 18)
                .addComponent(btn_dice)
                .addGap(18, 18, 18)
                .addComponent(btn_whatnumber)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//=======================MENU SECTION==================================
    private void btn_lowehighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lowehighActionPerformed
		highlow.setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_btn_lowehighActionPerformed
    private void btn_headtailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_headtailActionPerformed
		this.setVisible(false);
		headtail.setVisible(true);
    }//GEN-LAST:event_btn_headtailActionPerformed
    private void btn_diceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_diceActionPerformed
    {//GEN-HEADEREND:event_btn_diceActionPerformed
		this.setVisible(false);
		dice.setVisible(true);
    }//GEN-LAST:event_btn_diceActionPerformed
    private void btn_whatnumberActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_whatnumberActionPerformed
    {//GEN-HEADEREND:event_btn_whatnumberActionPerformed
		this.setVisible(false);
		whatnum.setVisible(true);
    }//GEN-LAST:event_btn_whatnumberActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				//at the begining we start all games and showing only StartWindow
				highlow = new HigherLower();
				headtail = new HeadTail();
				dice = new Dice();
				whatnum = new Whatnumber();
				new StartWindow().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dice;
    private javax.swing.JButton btn_headtail;
    private javax.swing.JButton btn_lowehigh;
    private javax.swing.JButton btn_whatnumber;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
