
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * This class is resposible for "What number I'm thinking of" game and frame.
 *
 * @author kastel
 */
public class Whatnumber extends javax.swing.JFrame
{

	/**
	 * Random generator
	 */
	private Random rnd;

	/**
	 * Set range of draw numbers
	 */
	private int range;

	/**
	 * Luckly number
	 */
	private int number;
	/**
	 * Counter of how many times you tried to guess
	 */
	private int counter;
	/**
	 * The lowest number of tries
	 */
	private int highscore;

	/**
	 * Creates new form Whatnumber
	 */
	public Whatnumber()
	{
		initComponents();
		this.setLocationRelativeTo(null);		//center of screen
		IntegerDocumentFilter.addTo(txtb_numb); //prevent from entering something else than digits

		//initialization
		rnd = new Random();
		range = 1000;	//setting the range 
		number = rnd.nextInt(1000); //set the lucky number
		counter = 0;	//reset counter
		highscore = Integer.MAX_VALUE;	//highest avaiable number

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        txtb_numb = new javax.swing.JTextField();
        btn_guess = new javax.swing.JButton();
        lbl_result = new javax.swing.JLabel();
        lbl_counter = new javax.swing.JLabel();
        lbl_highscore = new javax.swing.JLabel();
        result_lbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        runHigherLower = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        runHeadTail = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        runDice = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        runWhatnum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("What number?");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("I am thinking about number...?");

        txtb_numb.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_guess.setBackground(new java.awt.Color(102, 153, 255));
        btn_guess.setText("I am guessing!");
        btn_guess.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_guessActionPerformed(evt);
            }
        });

        lbl_result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_counter.setText("0");
        lbl_counter.setToolTipText("How many times you tried");

        lbl_highscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_highscore.setText("0");
        lbl_highscore.setToolTipText("How many times you tried");

        result_lbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        result_lbl.setText("Highscore:");
        result_lbl.setToolTipText("How many times you tried");

        jMenu1.setText("LowerHigher");

        runHigherLower.setText("Run");
        runHigherLower.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runHigherLowerActionPerformed(evt);
            }
        });
        jMenu1.add(runHigherLower);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Head or Tails");

        runHeadTail.setText("Run");
        runHeadTail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runHeadTailActionPerformed(evt);
            }
        });
        jMenu2.add(runHeadTail);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dice");

        runDice.setText("Run");
        runDice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runDiceActionPerformed(evt);
            }
        });
        jMenu3.add(runDice);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("What number?");
        jMenu4.setEnabled(false);

        runWhatnum.setText("Run");
        runWhatnum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runWhatnumActionPerformed(evt);
            }
        });
        jMenu4.add(runWhatnum);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtb_numb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(result_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_highscore, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_counter, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtb_numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guess, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_counter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_highscore)
                    .addComponent(result_lbl))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//=======================MENU SECTION==================================
    private void runHigherLowerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runHigherLowerActionPerformed
    {//GEN-HEADEREND:event_runHigherLowerActionPerformed
		this.setVisible(false);
		StartWindow.highlow.setVisible(true);
    }//GEN-LAST:event_runHigherLowerActionPerformed
    private void runHeadTailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runHeadTailActionPerformed
    {//GEN-HEADEREND:event_runHeadTailActionPerformed
		this.setVisible(false);
		StartWindow.headtail.setVisible(true);
    }//GEN-LAST:event_runHeadTailActionPerformed
    private void runDiceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runDiceActionPerformed
    {//GEN-HEADEREND:event_runDiceActionPerformed
		this.setVisible(false);
		StartWindow.dice.setVisible(true);
    }//GEN-LAST:event_runDiceActionPerformed
    private void runWhatnumActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runWhatnumActionPerformed
    {//GEN-HEADEREND:event_runWhatnumActionPerformed
		this.setVisible(false);
		StartWindow.whatnum.setVisible(true);
    }//GEN-LAST:event_runWhatnumActionPerformed
	/**
	 * Checking your guess with correct answer.
	 * @param evt
	 */
    private void btn_guessActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_guessActionPerformed
    {//GEN-HEADEREND:event_btn_guessActionPerformed
		//if field is not empty
		if (!txtb_numb.getText().isEmpty())
		{
			//get the value and compare
			int guess = Integer.parseInt(String.valueOf(txtb_numb.getText()));
			
			//if lower
			if (guess < number)
			{
				//if lower but close
				if (guess + 15 >= number)
				{
					lbl_result.setText("Number is higher but you are close!");
				}
				else
				{
					lbl_result.setText("My number is higher! Try again!");
				}
				counter++;
				txtb_numb.setText("");
				lbl_counter.setText(String.valueOf(counter));
			}
			//if higher
			else if (guess > number)
			{
				//if higher but close
				if (guess - 15 <= number)
				{
					lbl_result.setText("Number is lower but you are close!");
				}
				else
				{
					lbl_result.setText("My number is lower! Try again!");
				}
				counter++;
				lbl_counter.setText(String.valueOf(counter));
			}
			else //you guessed
			{
				//if you are the best
				if (counter <= highscore)
				{
					highscore = counter;
					lbl_highscore.setText(String.valueOf(counter));
				}
				//show message about win
				lbl_result.setText("Correct! My number is " + number + "!");
				lbl_counter.setText("Answered after: " + counter + " attempts!");
				JOptionPane.showMessageDialog(null, "You guessed!", "Success!", JOptionPane.INFORMATION_MESSAGE);

				//reset counter, play again
				counter = 0;
				number = rnd.nextInt(range);
			}
		}
		else
		{
			JOptionPane.showMessageDialog(null, "You must enter the number!", "Fill blank", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btn_guessActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new Whatnumber().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_counter;
    private javax.swing.JLabel lbl_highscore;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel result_lbl;
    private javax.swing.JMenuItem runDice;
    private javax.swing.JMenuItem runHeadTail;
    private javax.swing.JMenuItem runHigherLower;
    private javax.swing.JMenuItem runWhatnum;
    private javax.swing.JTextField txtb_numb;
    // End of variables declaration//GEN-END:variables
}
