/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * This class is resposible for "What number I'm thinking of" game and frame.
 *
 * @author kastel
 */
public class Whatnumber extends javax.swing.JFrame
{

	/**
	 * Creates new form Whatnumber
	 */
	public Whatnumber()
	{
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        runHigherLower = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        runHeadTail = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        runDieces = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        runWhatnum = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("What number?");
        setResizable(false);

        jMenu1.setText("LowerHigher");

        runHigherLower.setText("Run");
        runHigherLower.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runHigherLowerActionPerformed(evt);
            }
        });
        jMenu1.add(runHigherLower);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Head or Tails");

        runHeadTail.setText("Run");
        runHeadTail.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runHeadTailActionPerformed(evt);
            }
        });
        jMenu2.add(runHeadTail);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dieces");

        runDieces.setText("Run");
        runDieces.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runDiecesActionPerformed(evt);
            }
        });
        jMenu3.add(runDieces);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("What number?");
        jMenu4.setEnabled(false);

        runWhatnum.setText("Run");
        runWhatnum.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                runWhatnumActionPerformed(evt);
            }
        });
        jMenu4.add(runWhatnum);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	//=======================MENU SECTION==================================
    private void runHigherLowerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runHigherLowerActionPerformed
    {//GEN-HEADEREND:event_runHigherLowerActionPerformed
		this.setVisible(false);
		StartWindow.highlow.setVisible(true);
    }//GEN-LAST:event_runHigherLowerActionPerformed
    private void runHeadTailActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runHeadTailActionPerformed
    {//GEN-HEADEREND:event_runHeadTailActionPerformed
		this.setVisible(false);
		StartWindow.headtail.setVisible(true);
    }//GEN-LAST:event_runHeadTailActionPerformed
    private void runDiecesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runDiecesActionPerformed
    {//GEN-HEADEREND:event_runDiecesActionPerformed
		this.setVisible(false);
		StartWindow.dice.setVisible(true);
    }//GEN-LAST:event_runDiecesActionPerformed
    private void runWhatnumActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_runWhatnumActionPerformed
    {//GEN-HEADEREND:event_runWhatnumActionPerformed
		this.setVisible(false);
		StartWindow.whatnum.setVisible(true);
    }//GEN-LAST:event_runWhatnumActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(Whatnumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new Whatnumber().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem runDieces;
    private javax.swing.JMenuItem runHeadTail;
    private javax.swing.JMenuItem runHigherLower;
    private javax.swing.JMenuItem runWhatnum;
    // End of variables declaration//GEN-END:variables
}
